export enum RoleName {
  ADMIN = 'ADMIN',
  RECRUITER = 'RECRUITER',
  EMPLOYER = 'EMPLOYER',
  AGENT = 'AGENT',
  CANDIDATE = 'CANDIDATE',
  AUDITOR = 'AUDITOR',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}

export enum Proficiency {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  FLUENT = 'FLUENT',
  NATIVE = 'NATIVE',
}

export enum DemandStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
}

export enum CandidateStatus {
  NEW = 'NEW',
  SCREENED = 'SCREENED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  SELECTED = 'SELECTED',
  MEDICAL_PENDING = 'MEDICAL_PENDING',
  VISA_PROCESSING = 'VISA_PROCESSING',
  MOFA_SUBMITTED = 'MOFA_SUBMITTED',
  DEPLOYED = 'DEPLOYED',
  REJECTED = 'REJECTED',
}

export enum InterviewResult {
  PENDING = 'PENDING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  RESCHEDULED = 'RESCHEDULED',
  CANCELLED = 'CANCELLED',
}

export enum MedicalStatus {
  PENDING = 'PENDING',
  FIT = 'FIT',
  UNFIT = 'UNFIT',
  REEXAMINE = 'REEXAMINE',
}

export enum VisaStatus {
  PENDING = 'PENDING',
  APPLIED = 'APPLIED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  STAMPED = 'STAMPED',
}

export enum MOFAStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum DeploymentStatus {
  PENDING = 'PENDING',
  TICKET_ISSUED = 'TICKET_ISSUED',
  DEPARTED = 'DEPARTED',
  ARRIVED = 'ARRIVED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  PASSPORT = 'PASSPORT',
  CITIZENSHIP = 'CITIZENSHIP',
  MEDICAL = 'MEDICAL',
  POLICE_CLEARANCE = 'POLICE_CLEARANCE',
  CERTIFICATE = 'CERTIFICATE',
  PHOTO = 'PHOTO',
  RESUME = 'RESUME',
  VISA = 'VISA',
  CONTRACT = 'CONTRACT',
  OTHER = 'OTHER',
}

export enum NotificationType {
  SYSTEM = 'SYSTEM',
  INTERVIEW = 'INTERVIEW',
  VISA = 'VISA',
  MEDICAL = 'MEDICAL',
  DEPLOYMENT = 'DEPLOYMENT',
  GENERAL = 'GENERAL',
}

export enum ResumeStatus {
  NEW = 'NEW',
  PENDING = 'PENDING',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEWED = 'INTERVIEWED',
  REJECTED = 'REJECTED',
}
